### ISSUE TITLE
To add: D47 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#44]
Data:
provided by Laurent Arnaud (IGE)
Pub:
Arnaud, L., Lipenkov, V., Barnola, J.-M., Gay, M. and Duval, P.: Modelling of the densification of polar firn: characterization of the snow-firn transition, in Annals of Glaciology, vol. 26, pp. 39–44., 1998

**Comment by BaptisteVandecrux** [comment]
added in 2024 release
