### ISSUE TITLE
To add: Dome A density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#47]
Data:
provided as personal communication by Xiao Cunde to Patricia Martinerie (IGE)
Pub:
Cunde, X., Yuansheng, L., Allison, I., Shugui, H., Dreyfus, G., Barnola, J., . . . Kameda, T. (2008). Surface characteristics at Dome A, Antarctica: First measurements and a guide to future ice-coring sites. Annals of Glaciology, 48, 82-87. doi:10.3189/172756408784700653

**Comment by BaptisteVandecrux** [comment]
added
