### ISSUE TITLE
To add: Miege et al. 2020 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#53]
Data:
Miège, C., Forster, R., Koenig, L., Miller, J., Miller, O., Montgomery, L., et al. (2020) "Density, hydrology and geophysical measurements from the Wilkins Ice Shelf firn aquifer" U.S. Antarctic Program (USAP) Data Center. doi: https://doi.org/10.15784/601390
Pub:
Montgomery, L., Miège, C., Miller, J., Scambos, T. A., Wallin, B., Miller, O., et al. (2020). Hydrologic properties of a highly permeable firn aquifer in the Wilkins Ice Shelf, Antarctica. Geophysical Research Letters, 47, e2020GL089552. https://doi.org/10.1029/2020GL089552

**Comment by BaptisteVandecrux** [comment]
Already part of SUMup 2022 as ref 193 profiles 1940 to 1944.
