### ISSUE TITLE
To add: Winski et al. 2019 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#54]
Data:
Winski, D. A., Alley, R., Aydin, M., Bay, R., Beaudette, R., Brook, E. J., et al. (2019) "The South Pole Ice Core (SPICEcore) chronology and supporting data" U.S. Antarctic Program (USAP) Data Center. doi: https://doi.org/10.15784/601206
Pub:
Winski, D. A., Fudge, T. J., Ferris, D. G., Osterberg, E. C., Fegyveresi, J. M., Cole-Dai, J., Thundercloud, Z., Cox, T. S., Kreutz, K. J., Ortman, N., Buizert, C., Epifanio, J., Brook, E. J., Beaudette, R., Severinghaus, J., Sowers, T., Steig, E. J., Kahle, E. C., Jones, T. R., Morris, V., Aydin, M., Nicewonger, M. R., Casey, K. A., Alley, R. B., Waddington, E. D., Iverson, N. A., Dunbar, N. W., Bay, R. C., Souney, J. M., Sigl, M., and McConnell, J. R. (2019) The SP19 chronology for the South Pole Ice Core – Part 1: volcanic matching and annual layer counting, Clim. Past, 15, 1793–1808 ([doi:10.5194/cp-15-1793-2019](https://doi.org/10.5194/cp-15-1793-2019))

**Comment by BaptisteVandecrux** [comment]
Now added to 2024 version
