### ISSUE TITLE
To add: Winstrup et al. 2019 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#58]
Data:
archived at https://doi.org/10.1594/PANGAEA.899147 (Winstrup et al., 2019) and are also available in the Supplement
Pub:
Winstrup, M., Vallelonga, P., Kjær, H. A., Fudge, T. J., Lee, J. E., Riis, M. H., Edwards, R., Bertler, N. A. N., Blunier, T., Brook, E. J., Buizert, C., Ciobanu, G., Conway, H., Dahl-Jensen, D., Ellis, A., Emanuelsson, B. D., Hindmarsh, R. C. A., Keller, E. D., Kurbatov, A. V., Mayewski, P. A., Neff, P. D., Pyne, R. L., Simonsen, M. F., Svensson, A., Tuohy, A., Waddington, E. D., and Wheatley, S.: A 2700-year annual timescale and accumulation history for an ice core from Roosevelt Island, West Antarctica, Clim. Past, 15, 751–779, https://doi.org/10.5194/cp-15-751-2019, 2019

**Comment by BaptisteVandecrux** [comment]
This was added in the 2024 release
