### ISSUE TITLE
To add: Stevens et al. 2023 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#59]
Data:
Stevens, C., Conway, H., Fudge, T. J., Koutnik, M., Lilien, D., & Waddington, E. D. (2023) "Firn density and compaction rates 50km upstream of South Pole" U.S. Antarctic Program (USAP) Data Center. doi: https://doi.org/10.15784/601680
Pub:
none

**Comment by BaptisteVandecrux** [comment]
added.

Missing info:
- elevation
- date for each profile
- whether reported depth are top, mid or bottom.
