### ISSUE TITLE
To add: Picard et al. 2022 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#60]
Data:
Snow properties in Antarctica, Canada and the Alps for microwave emission and backscatter modeling. doi:10.18709/perscido.2022.05.ds367
Pub:
G. Picard, H. Löwe, F. Domine, L. Arnaud, F. Larue, V. Favier, E. Le Meur, E. Lefebvre, J. Savarino, A. Royer, The microwave snow grain size: a new concept to predict Satellite observations over snow-covered regions, AGU Advances, 3, 4, e2021AV000630, doi:10.1029/2021AV000630

**Comment by BaptisteVandecrux** [comment]
Added to 2024 version
