### ISSUE TITLE
To add: Fourteau et al. 2019b density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#62]
Data:
Fourteau, Kévin; Arnaud, Laurent; Faïn, Xavier; Martinerie, Patricia; Etherdige, David M; Lipenkov, Vladimir Ya; Barnola, Jean-Marc (2019): Gas pycnometry firn porosity data of firn ice cores from three polar sites. PANGAEA, https://doi.org/10.1594/PANGAEA.907678
Pub:
Fourteau, K., Arnaud, L., Faïn, X., Martinerie, P., Etheridge, D. M., Lipenkov, V., and Barnola, J.-M.: Historical porosity data in polar firn, Earth Syst. Sci. Data, 12, 1171–1177, https://doi.org/10.5194/essd-12-1171-2020, 2020

**Comment by BaptisteVandecrux** [comment]
added
