### ISSUE TITLE
To add: Fernandoy et al. 2010 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#64]
Data:
Fernandoy, Francisco; Meyer, Hanno; Oerter, Hans; Wilhelms, Frank; Graf, Wolfgang; Schwander, Jakob (2010): High resolution delta18O, conductivity, and density of firn core DML641C02_01. PANGAEA, https://doi.org/10.1594/PANGAEA.753182
Pub:
Fernandoy, F et al. (2010): Temporal and Spatial variation of stable-isotope ratios and accumulation rates in the hinterland of Neumayer station, East Antarctica. Journal of Glaciology, 56(198), 673-687, https://doi.org/10.3189/002214310793146296

**Comment by BaptisteVandecrux** [comment]
already added as profile 820
