### ISSUE TITLE
To add: Mayewski 1998 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#65]
Data:
Mayewski, P., 1998, Newall Glacier Ice Core Data. International Ice Core Data Cooperative. IGBP Pages/World Data Center-A for Paleoclimatology, NOAA/NGDC Paleoclimatology Program, Boulder CO, USA. 
ftp://ftp.ncdc.noaa.gov/pub/data/paleo/icecore/antarctica/newall/core_density.txt 
Pub:
Mayewski, P.A. et al., 1995, An Ice-core based, late Holocene history for the Transantarctic mountains, Antarctica.  Contributions to Antarctic Research IV, Antarctic Res. Series, 67, 33-45.

**Comment by BaptisteVandecrux** [comment]
Already added as ref 191
