### ISSUE TITLE
To add: Albert 2015 density data

### ISSUE THREAD

**Issue by charlesamory** [SUMup-database/SUMup-data-suggestion#66]
Data:
Albert, M. R. (2015) "Firn Permeability and Density at WAIS Divide" U.S. Antarctic Program (USAP) Data Center. doi: https://doi.org/10.7265/N57942NT
Pub: 
Gregory, S. A., Albert, M. R., and Baker, I.: Impact of physical properties and accumulation rate on pore close-off in layered firn, The Cryosphere, 8, 91–105, https://doi.org/10.5194/tc-8-91-2014, 2014

**Comment by BaptisteVandecrux** [comment]
added
