### ISSUE TITLE
To add: Leverett catchment, manual ablation observations, Chandler et al. 2015

### ISSUE THREAD

**Issue by davemchandler** [SUMup-database/SUMup-data-suggestion#73]
Surface ablation rates were measured daily using changes in ice surface height at five ablation stakes arranged in a cross configuration at ~2 m separation. The stakes were located in the supraglacial hydrological catchment feeding Moulin L41A (Chandler et al. 2021: https://doi.org/10.1016/j.epsl.2021.116982). The stakes were installed in holes deeper than the length of the stake (so each measurement of ice surface height was made from the ice surface down to the top of the stake) to avoid the problem of enhanced surface melting caused by solar radiation absorbed by the stake. All ablation measurements were carried out by the same observer to ensure consistency for example in the interpretation of the level of a rough ice surface. For full details see Chandler et al. (2015) at https://doi.org/10.5194/tc-9-487-2015.

Latitude: 66.97, Longitude: -49.27

Daily measurements, 30 May to 11 Aug 2012.

Data are archived at https://doi.pangaea.de/10.1594/PANGAEA.926842

**Comment by BaptisteVandecrux** [comment]
Added in the 2024 release
