### ISSUE TITLE
duplicate Greenland pit data

### ISSUE THREAD

**Issue by jasonebox** [SUMup-database/SUMup-data-suggestion#75]
The good news here is that correct data appear in SUMup, while for several sites there are duplicate values that lack date. The duplicate/bad site data use the correct longer version of the name, e.g. Crawford Point while the correct data use the site name abreviation, in this case CP1.

The best-practice fix for this issue, detailed in several examples below, would seem to be to use the full name, e.g. South Dome instead of SDM, along with the more correct data (that include the measurement date, i.e., the "end_date")

first example:

bad news:
measurement_ids: 304530 and 304531 have identical values
for site name: Crawford Point
and another error is for these measurement_ids start_year = end_year

good news:
... the measurement_id 304517 for name: CP1 has the correct smb value and the correct start_year and end_year

the fix:
as I see it, is to remove measurement_ids: 304530 and 304531

**Comment by jasonebox** [comment]
similarly for name: DYE-2, there are duplicates where the good values have the name DY2. Therefore, the fix seems to be to simply remove measurement_ids: 304539 through 304544

![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/d55ea607-7a08-4820-ab1f-e720f249f800)

**Comment by jasonebox** [comment]
another redundancy is measurement_id: 304516 for CP1 that is empty for start date and end date and has an identical smb with measurement_id: 304515

the fix appears to be to remove measurement_id: 304516

![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/205aa257-901f-4af4-b02c-94a2ae7f9726)

**Comment by jasonebox** [comment]
similar issue, redundancy and end_date issue for South Dome with correct data under the name SDM
![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/be227b2d-89d6-41c4-aa32-4af832ac3b18)
here are the duplicate/erroneous South Dome data
![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/402b167d-98eb-4baf-98d3-f7783196d6d2)

the best-practice fix for this general issue would seem to be to use the full name, e.g. South Dome instead of SDM, along with the more correct data (that include the measurement date, the end_date)

**Comment by jasonebox** [comment]
For Saddle, I find no SDL data (good news I think), but there are date and duplication issues, years 2008, 2010, 2013:
![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/7d9c931c-42b4-464a-877e-cc11105f24ff)

**Comment by BaptisteVandecrux** [comment]
I identified the origin of the duplication and removed it from the next release.
Thanks for the heads up!

**Comment by BaptisteVandecrux** [comment]
these duplicates have been removed from the now-released 2024 data
