### ISSUE TITLE
Greenland pit data missing date

### ISSUE THREAD

**Issue by jasonebox** [SUMup-database/SUMup-data-suggestion#76]
For nanok, the end_date was recorded by field workers but does not appear in SUMup. 

![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/49e60317-bf35-4e77-a4fd-f2c0a92b848d)

I need end_date for my analysis

**Comment by jasonebox** [comment]
similarly for Swiss Camp
![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/208b7b81-db82-473c-bcbc-25799682de93)

**Comment by jasonebox** [comment]
similarly for NEEM
![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/dc9435b7-0b2e-46d7-aad7-febe87303813)
and some cases for Petermann
![image](https://github.com/SUMup-database/SUMup-data-suggestion/assets/32133350/d37612e8-de0f-4d63-b519-c70dacbf9df7)
note for Petermann, the site could be either the Petermann ELA or the Petermann Gl. site (2 distinct sites)

**Comment by BaptisteVandecrux** [comment]
Thanks Jason, I've spotted the bug. It will be fixed in the next release.
Let me know if you need a patched 2023 version in the meantime.

**Comment by BaptisteVandecrux** [comment]
The correct dates have been added to the now-released 2024 data
